config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends

  get 'home/about', as: :about
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'

  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord

  validates :first_name, presence: true
  validates :last_name, presence: true

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # def redirect_after_signin
  #   root_path
  # end

  # def after_sign_in_path_for(resource)
  #   root_path
  # end


end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = current_user ? current_user.friends : []
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new({ **friend_params, user_id: current_user.id })

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find_by(id: params[:id])
      if @friend
        redirect_to friends_path unless @friend.user_id == current_user.id
      end
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :phone_number, :email, :twitter)
    end

    # Only allow a user to edit/destroy friend if that friend is theirs
    def authorized_user!
      redirect_back_or_to friends_path unless @friend.user_id == current_user.id
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<div class="d-flex flex-column justify-content-between align-items-center p-5 bg-dark bg-opacity-25 w-50 m-auto rounded">
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <div>
      <%= form.label :first_name, style: "display: block" %>
      <%= form.text_field :first_name %>
    </div>

    <div>
      <%= form.label :last_name, style: "display: block" %>
      <%= form.text_field :last_name %>
    </div>

    <div>
      <%= form.label :phone_number, style: "display: block" %>
      <%= form.text_field :phone_number %>
    </div>

    <div>
      <%= form.label :email, style: "display: block" %>
      <%= form.text_field :email %>
    </div>

    <div>
      <%= form.label :twitter, style: "display: block" %>
      <%= form.text_field :twitter %>
    </div>

    <div>
      <%= form.submit class:"btn btn-info" %>
    </div>

<% end %>
</div>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= friend.phone_number %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

  <p>
    <strong>Friend Since:</strong>
    <%= friend.created_at.strftime("%m-%d-%Y") %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<h1>Friends</h1>

<div id="friends">
  <table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Phone</th>
      <th scope="col">Email</th>
      <th scope="col">Twitter</th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td>
          <% display_name = "#{friend.first_name} #{friend.last_name}" %>
          <% display_name = display_name.length > 50 ? "#{display_name[0,46]}..." : display_name %>
          <%= link_to display_name, friend_path(friend) %>
        </td>
        <td> <%= friend.phone_number %> </td>
        <td> <%= friend.email %> </td>
        <td> <%= friend.twitter %> </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "New friend", new_friend_path, class:"btn btn-primary" %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/show.html.erb
<div class="d-flex justify-content-between p-5 bg-dark bg-opacity-25 w-75 m-auto rounded">

<div>
<%= render @friend %>
</div>

<div class="d-flex flex-column justify-content-between">
  <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-dark" %>
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>
  <%= button_to "Destroy this friend", @friend, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' }}, class:"btn btn-danger" %>
</div>

</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Friend App", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About", about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Friends", friends_path, class:"nav-link" %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<h1>Hello, World!</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-success %> alert-dismissible fade show" role="alert">
  <strong> <%= notice %> </strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Friend App", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About", about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <% if current_user %>
            <%= link_to "Friends", friends_path, class:"nav-link" %>
          <% end %>
        </li>
      </ul>
      <div>
        <% if user_signed_in? %>
          <%= link_to "Logout", destroy_user_session_path, class:"btn btn-primary", method: :delete %>
          <%= link_to "Edit Profile", edit_user_registration_path, class:"btn btn-info" %>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class:"btn btn-primary" %>
          <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-info" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Friends App</title>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>

      </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>